name: Build and Deploy Strapi

on:
  push:
    branches:
      - main
    
jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ghcr.io/omgg-dev/omgg-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.prod
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: omggWebsiteStrapiProd
      IMAGE_NAME: ghcr.io/omgg-dev/omgg-backend
      APP_PORT: 1337
    needs: build-and-push
    steps:
      - name: Connect via SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: CONTAINER_NAME, IMAGE_NAME, APP_PORT
          script: |
            docker pull ${{ env.IMAGE_NAME }}:latest
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            docker run -d \
              --name ${{ env.CONTAINER_NAME }} \
              -p ${{ env.APP_PORT }}:${{ env.APP_PORT }} \
              --env-file /home/ubuntu/omgg-backend/.env.prod \
              ${{ env.IMAGE_NAME }}:latest